web/feat.web/Models/Course.cs
using feat.common.Models.Enums;

namespace feat.web.Models;

public class Course
{
    public required Guid Id { get; set; }
    
    public required Guid InstanceId { get; set; }
        
    public required string Title { get; set; }
        
    public string? Provider { get; set; }
    
    public CourseType? CourseType { get; set; }
    
    public LearningMethod? DeliveryMode { get; set; }
    
    public bool? IsNational { get; set; }
    
    public string? Requirements { get; set; }
    
    public string? Overview { get; set; }
    
    public GeoLocation? Location { get; set; }
    
    public string? LocationName { get; set; }
    
    public double? Distance { get; set; }
}

web/feat.web/Models/Location.cs
namespace feat.web.Models;

public class Location
{
    public string? Name { get; set; }
    
    public string? Address1 { get; set; }
    
    public string? Address2 { get; set; }
    
    public string? Address3 { get; set; }
    
    public string? Address4 { get; set; }
    
    public string? Town { get; set; }
    
    public string? County { get; set; }
    
    public string? Postcode { get; set; }
    
    public GeoLocation? GeoLocation { get; set; }
}

web/feat.web/Pages/AccessibilityStatement.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace feat.web.Pages;

public class AccessibilityStatement : PageModel
{
    public void OnGet()
    {
        
    }
}

web/feat.web/Pages/Age.cshtml.cs
using feat.web.Enums;
using feat.web.Extensions;
using feat.web.Models;
using feat.web.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace feat.web.Pages;

public class AgeModel(ILogger<AgeModel> logger) : PageModel
{
    [BindProperty]
    public AgeGroup? AgeGroup { get; set; }

    public required Search Search { get; set; }

    public IActionResult OnGet()
    {
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();

        if (!Search.Updated)
        {
            return RedirectToPage("Index");
        }

        if (Search.AgeGroup.HasValue)
        {
            AgeGroup = Search.AgeGroup;
        }

        Search.SetPage(PageName.Age);
        HttpContext.Session.Set("Search", Search);

        return Page();
    }

    public IActionResult OnPost()
    {
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();

        if (!ModelState.IsValid)
        {
            return Page();
        }

        if (AgeGroup.HasValue)
        {
            Search.AgeGroup = AgeGroup.Value;
        }

        Search.Updated = true;
        HttpContext.Session.Set("Search", Search);

        return RedirectToPage(PageName.CheckAnswers);
    }
}

web/feat.web/Pages/Ai.cshtml.cs
using feat.web.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace feat.web.Pages;

public class AiModel(StaticNavigationHandler staticNavigation) : PageModel
{
    public string? RefererUrl { get; private set; } = "";
    
    public void OnGet()
    {
        RefererUrl = staticNavigation.GetRefererUrl();
    }
}

web/feat.web/Pages/CheckAnswers.cshtml.cs
using feat.web.Enums;
using feat.web.Extensions;
using feat.web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using feat.web.Utils;

namespace feat.web.Pages;

public class CheckAnswersModel (ILogger<CheckAnswersModel> logger): PageModel
{
    public required Search Search { get; set; }
    
    public IActionResult OnGet()
    {
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();
        
        if (!Search.Updated)
        {
            return RedirectToPage("Index");
        }

        HttpContext.Session.Remove("AllFacets");
        Search.Facets.Clear();
        
        Search.SetPage(PageName.CheckAnswers);
        Search.ResetHistory(PageName.CheckAnswers);
        
        HttpContext.Session.Set("Search", Search);

        if (Search.Interests.Count == 0 && (Search.Distance is null or < Distance.Two) && 
            Search.QualificationLevels.Count == 0 && Search.VisitedCheckAnswers)
        {
            return RedirectToPage(PageName.Location);
        }
        
        return Page();
    }

    public IActionResult OnPost()
    {
        try
        {
            Search = HttpContext.Session.Get<Search>("Search") ?? new Search();
            
            Search.Updated = true;
            HttpContext.Session.Set("Search", Search);

            return RedirectToPage(PageName.LoadCourses);
        }
        catch (Exception e)
        {
            logger.LogError(e.Message);
            throw;
        }
    }
}

web/feat.web/Pages/Cookies.cshtml.cs
using feat.web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace feat.web.Pages;

public class Cookies : PageModel
{
    [BindProperty] 
    public string? AnalyticsCookie { get; set; }
    
    [BindProperty]
    public string? MarketingCookie { get; set; }
    
    public void OnGet()
    {
        var analyticsCookieValue = Request.Cookies["analytics-cookies"];
        var matketingCookieValue = Request.Cookies["marketing-cookies"];
        
        if (analyticsCookieValue != null)
        {
            AnalyticsCookie = analyticsCookieValue;
        }
        if (analyticsCookieValue != null)
        {
            MarketingCookie = matketingCookieValue;
        }
        
    }

    public void OnPost()
    {
        Response.Cookies.Append("analytics-cookies", "true");
        Response.Cookies.Append("marketing-cookies", "true");
    }
}

web/feat.web/Pages/Course.cshtml.cs
using feat.web.Models.ViewModels;
using feat.web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace feat.web.Pages;

public class CourseModel(ISearchService searchService, StaticNavigationHandler staticNavigation) : PageModel
{
    public CourseDetailsBase? Course { get; private set; }
    
    public string? RefererUrl { get; private set; } = "";

    public async Task<IActionResult> OnGet(Guid instanceId)
    {
        RefererUrl = staticNavigation.GetRefererUrl();
        
        Course = await searchService.GetCourseDetails(instanceId.ToString());

        if (Course == null)
        {
            return NotFound();
        }
        
        return Page();
    }
}

web/feat.web/Pages/Index.cshtml.cs
using feat.web.Extensions;
using feat.web.Models;
using feat.web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using feat.web.Utils;

namespace feat.web.Pages;

public class IndexModel(StaticNavigationHandler staticNavigation,ILogger<IndexModel> logger) : PageModel
{
    public IActionResult OnGet()
    {
        var search = new Search();
        
        search.SetPage(PageName.Index);
        staticNavigation.Initialise();
        HttpContext.Session.Set("Search", search);
        
        return Page();
    }
}

web/feat.web/Pages/LoadCourses.cshtml.cs
using feat.web.Enums;
using feat.web.Extensions;
using feat.web.Models;
using feat.web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using feat.web.Utils;

namespace feat.web.Pages;

public class LoadCoursesModel(ISearchService searchService, ILogger<LoadCoursesModel> logger) : PageModel
{   
    [BindProperty]
    public Distance? SelectedTravelDistance { get; set; }
    
    public required Search Search { get; set; }
    
    public List<Course> Courses { get; set; } = [];
    
    public int TotalCourseCount { get; private set; }
    
    [BindProperty]
    public List<Models.ViewModels.Facet> AllFacets { get; set; } = [];
    
    // Pagination 
    public int CurrentPage { get; set; } = 1;
    public int TotalPages { get; set; }
    public int PageSize { get; set; } = 10;
    
    public bool HasPreviousPage => CurrentPage > 1;
    public bool HasNextPage => CurrentPage < TotalPages;
    public int PreviousPage => CurrentPage - 1;
    public int NextPage => CurrentPage + 1;
    
    public async Task<IActionResult> OnGetAsync(string orderBy, int pageNumber = 1) 
    {
        pageNumber = pageNumber < 1 ? 1 : pageNumber;
        
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();
        
        if (!Search.Updated)
        {
            return RedirectToPage(PageName.Index);
        }
        
        Search.CurrentPage = pageNumber;
        Search.TotalPages = TotalPages;
        Search.PageSize = PageSize;

        if (!string.IsNullOrEmpty(orderBy))
        {
            Search.OrderBy = orderBy.Equals("distance", StringComparison.InvariantCultureIgnoreCase) 
                ? OrderBy.Distance 
                : OrderBy.Relevance;
        }
        else if (Search.Interests.Count == 0)
        {
            Search.OrderBy = OrderBy.Distance;
        }
        
        Search.SetPage(PageName.LoadCourses);
        HttpContext.Session.Set("Search", Search);
        
        var searchResponse = await searchService.Search(Search, HttpContext.Session.Id);
        
        Courses = searchResponse.Courses.ToList();
        TotalCourseCount = searchResponse.TotalCount;
        CurrentPage = searchResponse.Page;
        PageSize = searchResponse.PageSize;
        TotalPages = (int)Math.Ceiling(searchResponse.TotalCount / (double)searchResponse.PageSize);
        
        var searchResponseFacets = searchResponse.Facets.ToViewModels();
        var sessionFacets = HttpContext.Session.Get<List<Models.ViewModels.Facet>>("AllFacets");
        
        if (searchResponseFacets.Count != 0)
        {
            AllFacets = searchResponseFacets;
            
        }
        else if (sessionFacets != null)
        {
            AllFacets = sessionFacets;
        }
        
        if (Search.Facets.Count == 0) // Initial search
        {
            if (Courses.Count == 0)
            {
                return RedirectToPage(PageName.NoResultsSearch);
            }
            
            SelectQualificationLevels();
            Search.Facets = AllFacets;
        }
        
        if (sessionFacets != null)
        {
            foreach (var facet in AllFacets)
            {
                var sessionFacet = sessionFacets.FirstOrDefault(f => f.Name == facet.Name);
                if (sessionFacet != null)
                {
                    foreach (var value in facet.Values)
                    {
                        var sessionValue = sessionFacet.Values.FirstOrDefault(v => v.Name == value.Name);
                        
                        if (sessionValue != null)
                        {
                            value.Selected = sessionValue.Selected;
                        }
                    }
                }
            }
        }
        
        HttpContext.Session.Set("AllFacets", AllFacets);
        Search.Facets = AllFacets;
        
        SelectedTravelDistance = Search.Distance;

        return Page();
    }

    public IActionResult OnGetClearFilters()
    {
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();
        
        HttpContext.Session.Remove("AllFacets");
        AllFacets = [];
        
        Search.Facets = [];
        Search.CurrentPage = 1;
        
        Search.Distance = Search.OriginalDistance;
        Search.QualificationLevels = [];
        
        HttpContext.Session.Set("Search", Search);
        
        return RedirectToPage();
    }
    
    public IActionResult OnGetClearFacet(string facetName)
    {
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();

        var allFacets = HttpContext.Session.Get<List<Models.ViewModels.Facet>>("AllFacets") ?? [];
        
        var facet = allFacets.FirstOrDefault(f =>
            f.Name.Equals(facetName, StringComparison.InvariantCultureIgnoreCase));

        if (facet != null)
        {
            foreach (var value in facet.Values)
            {
                value.Selected = false;
            }
        }
        
        Search.Facets = allFacets;
        Search.CurrentPage = 1;

        HttpContext.Session.Set("AllFacets", allFacets);
        HttpContext.Session.Set("Search", Search);

        return RedirectToPage();
    }

    public IActionResult OnPostUpdateSelection()
    {
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();
        Search.Distance = SelectedTravelDistance;
        
        MergeSelectedFacets(AllFacets);
        
        HttpContext.Session.Set("AllFacets", AllFacets);
        HttpContext.Session.Set("Search", Search);

        return RedirectToPage();
    }

    internal List<int> GetPageNumbers()
    {
        var pages = new List<int>();

        if (TotalPages <= 3)
        {
            for (var i = 1; i <= TotalPages; i++)
            {
                pages.Add(i);
            }
        }
        else
        {
            if (CurrentPage == 1)
            {
                pages.Add(1);
                pages.Add(2);
                pages.Add(3);
            }
            else if (CurrentPage == TotalPages)
            {
                // At the End - last 3 pages
                pages.Add(TotalPages - 2);
                pages.Add(TotalPages - 1);
                pages.Add(TotalPages);
            }
            else
            {
                // In the middle
                pages.Add(CurrentPage - 1);
                pages.Add(CurrentPage);
                pages.Add(CurrentPage + 1);
            }
        }
        return pages;
    }
    
    private void MergeSelectedFacets(List<Models.ViewModels.Facet>? postedFacets)
    {
        if (postedFacets == null || postedFacets.Count == 0)
        {
            return;
        }

        var fullFacets = HttpContext.Session.Get<List<Models.ViewModels.Facet>>("AllFacets") ?? [];

        if (fullFacets.Count == 0)
        {
            AllFacets = postedFacets;
            Search.Facets = postedFacets;
            
            return;
        }

        for (var pIndex = 0; pIndex < postedFacets.Count; pIndex++)
        {
            var posted = postedFacets[pIndex];

            Models.ViewModels.Facet? original = null;

            if (!string.IsNullOrEmpty(posted.Name))
            {
                original = fullFacets.FirstOrDefault(f =>
                    string.Equals(f.Name, posted.Name, StringComparison.InvariantCultureIgnoreCase));
            }

            if (original == null && pIndex < fullFacets.Count)
            {
                original = fullFacets[pIndex];
            }

            if (original == null)
            {
                continue;
            }

            var postedValues = posted.Values;

            for (var origValueIndex = 0; origValueIndex < original.Values.Count; origValueIndex++)
            {
                var originalValue = original.Values[origValueIndex];

                Models.ViewModels.FacetValue? postedValue = null;

                if (!string.IsNullOrEmpty(originalValue.Name))
                {
                    postedValue = postedValues.FirstOrDefault(v =>
                        string.Equals(v.Name, originalValue.Name, StringComparison.InvariantCultureIgnoreCase));
                }

                if (postedValue == null && origValueIndex < postedValues.Count)
                {
                    postedValue = postedValues[origValueIndex];
                }

                originalValue.Selected = postedValue?.Selected ?? false;
            }
        }

        AllFacets = fullFacets;
        Search.Facets = fullFacets;
    }

    private void SelectQualificationLevels()
    {
        const string name = nameof(SearchRequest.QualificationLevel);
        
        var facet = AllFacets
            .FirstOrDefault(f => f.Name.Equals(name, StringComparison.InvariantCultureIgnoreCase));
        
        if (facet != null)
        {
            var selectedOptions = Search.QualificationLevelMap
                .Where(x => Search.QualificationLevels.Contains(x.Key))
                .SelectMany(x => x.Value)
                .Select(x => ((feat.common.Models.Enums.QualificationLevel)x).ToString())
                .ToHashSet();
            
            foreach (var value in facet.Values)
            {
                value.Selected = selectedOptions.Contains(value.Name);
            }
        }
    }
}

web/feat.web/Pages/NoResultsSearch.cshtml.cs
using feat.web.Extensions;
using feat.web.Models;
using feat.web.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace feat.web.Pages;

public class NoResultsSearchModel(ILogger<NoResultsSearchModel> logger) : PageModel
{
    public required Search Search { get; set; }
    
    public IActionResult OnGet()
    {
        Search = HttpContext.Session.Get<Search>("Search") ?? new Search();
        
        if (!Search.Updated)
        {
            return RedirectToPage(PageName.Index);
        }
        
        Search.SetPage(PageName.NoResultsSearch);
        HttpContext.Session.Set("Search", Search);
        
        return Page();
    }
}

web/feat.web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace feat.web.Pages;

public class Privacy : PageModel
{
    public void OnGet()
    {
        
    }
}

web/feat.web/Pages/Index.cshtml
@page
@model feat.web.Pages.IndexModel
@using feat.web.Utils
@{
    ViewBag.PageTitle = "Find education and training opportunities";
}

<div class="govuk-width-container">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-l">@ViewBag.PageTitle</h1>
            <p>Whether you're already in education or training, or coming back after a break, we can help you work out what to do next.</p>
            
            <govuk-button-link asp-page="@PageName.Location" is-start-button="false">Start now</govuk-button-link>
        </div>
    </div>
</div>

web/feat.web/Pages/LoadCourses.cshtml
@page
@using feat.web.Enums
@using feat.web.Models.ViewModels
@using feat.web.Utils
@model feat.web.Pages.LoadCoursesModel

@{
  ViewBag.PageTitle = "Your search results";

  var totalResults = Model.TotalPages == 1 ? Model.Courses.Count : Model.TotalCourseCount;
  var pluralText = totalResults == 1 ? string.Empty : "s";
  var locationText = string.IsNullOrEmpty(Model.Search.Location) ? string.Empty : "near <strong>" + Model.Search.Location + "</strong>";
  var interestText = Model.Search.Interests.Count > 0 ? $"for <strong>{string.Join(", ", Model.Search.Interests)}</strong>" : string.Empty;
  var searchResultText = $"Showing {totalResults} course{pluralText} {locationText} {interestText}";
}

<div class="govuk-width-container">
  
    <div class="govuk-grid-row">
      <!--Header section -->
      <div class="govuk-grid-column-full">
        <h1 class="govuk-heading-l">@ViewBag.PageTitle</h1>
        <p class="govuk-body-l">@Html.Raw(searchResultText)</p>
        <p><a asp-page="@PageName.Location">Search again</a></p>
        <hr class="govuk-section-break govuk-section-break--xl govuk-section-break--visible">
      </div>
    </div>

    <div class="govuk-grid-row">
      <!--Filters-->
      <div class="govuk-grid-column-one-third">
        <button type="button"
                class="govuk-button govuk-button--secondary mobile-filter-toggle"
                data-module="govuk-button"
                id="filterToggleBtn"
                aria-expanded="true"
                aria-controls="filterSection">
          <span class="filter-toggle-text">Hide filters</span>
        </button>

        <div id="filter-panel" class="filter-container">
          <form method="post" asp-page-handler="UpdateSelection">
            <div class="filter-container">
              <div id="filterSection" class="filter-section">
                <div class="govuk-summary-card">
                  <div class="govuk-summary-card__title-wrapper">
                    <div class="filter-heading">
                      <h2 class="govuk-heading-m govuk-!-margin-bottom-0">Filter</h2>
                    </div>
                  </div>

                  <div class="govuk-summary-card__content">
                    <div class="govuk-summary-list">
                      @if (Model.AllFacets is { Count: > 0 })
                      {
                        var facetIndex = 0;

                        foreach (var facet in Model.AllFacets.OrderBy(f => f.Index))
                        {
                          var orderedFacetValues = facet.Values
                            .Where(v => v.Index >= 0)
                            .OrderBy(v => v.Index)
                            .ToList();
                          
                          if (facetIndex == 1 && Model.SelectedTravelDistance != null)
                          {
                            <div class="govuk-summary-list__row">
                              <div class="govuk-form-group">
                                <govuk-select for="SelectedTravelDistance">
                                  <govuk-select-label class="govuk-!-margin-top-4 govuk-!-font-weight-bold">
                                    Travel distance
                                  </govuk-select-label>
                                  @foreach (var option in Enum.GetValues<Distance>())
                                  {
                                    <govuk-select-item 
                                      value="@((int)option)"
                                      selected="@(Model.SelectedTravelDistance == option)">
                                      @option.GetDisplayName()
                                    </govuk-select-item>
                                  }
                                </govuk-select>
                              </div>
                            </div>
                          }
                          
                          <div class="govuk-summary-list__row">
                              <div class="govuk-form-group">
                                  <input type="hidden" name="AllFacets[@facetIndex].Name" value="@facet.Name" />

                                  <govuk-checkboxes name="facet-@facetIndex">
                                      <govuk-checkboxes-fieldset class="govuk-checkboxes--small">
                                          <govuk-checkboxes-fieldset-legend 
                                              is-page-heading="false" 
                                              class="govuk-fieldset__legend--s">
                                              @facet.DisplayName
                                          </govuk-checkboxes-fieldset-legend>

                                          @for (var valueIndex = 0; valueIndex < orderedFacetValues.Count; valueIndex++)
                                          {
                                              var facetValue = orderedFacetValues[valueIndex];

                                              <govuk-checkboxes-item
                                                  id="facet-@facetIndex-value-@valueIndex"
                                                  name="AllFacets[@facetIndex].Values[@valueIndex].Selected"
                                                  value="true"
                                                  checked="@(facetValue.Selected)">
                                                  @facetValue.DisplayName
                                              </govuk-checkboxes-item>
                                          }
                                      </govuk-checkboxes-fieldset>
                                  </govuk-checkboxes>
                                  
                                  @for (var valueIndex = 0; valueIndex < orderedFacetValues.Count; valueIndex++)
                                  {
                                      var facetValue = orderedFacetValues[valueIndex];

                                      <input type="hidden"
                                             name="AllFacets[@facetIndex].Values[@valueIndex].Name"
                                             value="@facetValue.Name" />

                                      <input type="hidden"
                                             name="AllFacets[@facetIndex].Values[@valueIndex].Selected"
                                             value="false" />
                                  }
                                  @if (orderedFacetValues.Exists(v => v.Selected))
                                  {
                                    <p class="govuk-body">
                                      <a class="govuk-link" asp-page-handler="ClearFacet" asp-route-facetname="@facet.Name" id="clear-facet-@facet.Name">Clear filter<span class="govuk-visually-hidden"> for @facet.DisplayName</span></a>
                                    </p>
                                  }
                              </div>
                          </div>

                          facetIndex++;
                        }
                      }
                      <button class="govuk-button govuk-!-margin-top-4" type="submit">Apply filters</button>
                      <p class="govuk-body">
                        <a class="govuk-link" asp-page-handler="ClearFilters">Clear all filters</a>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>

      <!-- Results Section (Right Column) -->
      <div class="govuk-grid-column-two-thirds">

        @if (!Model.Courses.Any())
        {
          <partial name="Partials/_NoResults" model="new NoResults { HasFilters = true }" />
        }
        else
        {
          <!-- Results & Pagination -->
          <h2 class="govuk-heading-m">Available courses</h2>
          
          <!-- Sort Region-->
          <p class="govuk-body govuk-!-margin-bottom-6">
            <span class="govuk-!-font-weight-bold">Sort courses by:</span>
            <span class="govuk-!-margin-left-2">
              @{
                if (Model.Search.Location == null)
                {
                  <span aria-current="true">Relevance</span>
                }
                else
                {
                  if (Model.Search.OrderBy == OrderBy.Distance)
                  {
                    <span aria-current="true">Distance</span>
                    <span> | </span> 
                    <a asp-page="@PageName.LoadCourses" asp-route-orderBy="relevance">Relevance</a>
                  }
                  else
                  {
                    <a asp-page="@PageName.LoadCourses" asp-route-orderBy="distance">Distance</a>
                    <span> | </span> 
                    <span aria-current="true">Relevance</span>
                  }
                }
              }
            </span>
          </p>
          
          @foreach (var searchResult in Model.Courses)
          {
            await Html.RenderPartialAsync("Partials/_SearchResult", searchResult.ToResultViewModel());
          }

          <!-- Pagination -->
            @if (Model.TotalPages > 1)
            {
              <nav class="govuk-pagination" aria-label="Pagination">
                @if (Model.HasPreviousPage)
                {
                  <div class="govuk-pagination__prev">
                    <a class="govuk-link govuk-pagination__link"
                       asp-route-pageNumber="@(Model.PreviousPage)"
                       aria-label="Previous Page, Page @(Model.PreviousPage)">
                      <svg class="govuk-pagination__icon govuk-pagination__icon--prev" xmlns="http://www.w3.org/2000/svg"
                           height="13" width="15" aria-hidden="true" focusable="false" viewBox="0 0 15 13">
                        <path d="m6.5938-0.0088125-6.7266 6.7266 6.7441 6.4062 1.377-1.449-4.1856-3.9768h12.896v-2h-12.984l4.2931-4.293-1.414-1.414z"></path>
                      </svg>
                      <span class="govuk-pagination__link-title">Previous<span class="govuk-visually-hidden"> page</span></span>
                    </a>
                  </div>
                }
                <ul class="govuk-pagination__list">
                  @foreach (var pageNumber in Model.GetPageNumbers())
                  {
                    @if (pageNumber == Model.CurrentPage)
                    {
                      <li class="govuk-pagination__item govuk-pagination__item--current">
                        <a class="govuk-link govuk-pagination__link"
                           asp-route-pageNumber="@pageNumber"
                           aria-label="@($"Current Page, Page {pageNumber}")" aria-current="page">
                          @pageNumber
                        </a>
                      </li>
                    }
                    else
                    {
                      <li class="govuk-pagination__item">
                        <a class="govuk-link govuk-pagination__link"
                           asp-route-pageNumber="@pageNumber"
                           aria-label="@($"Page {pageNumber}")">
                          @pageNumber
                        </a>
                      </li>
                    }
                  }
                </ul>
                
                @if (Model.HasNextPage)
                {
                  <div class="govuk-pagination__next">
                    <a class="govuk-link govuk-pagination__link"
                       asp-route-pageNumber="@Model.NextPage"
                       aria-label="Next Page, Page @(Model.NextPage)">
                      <span class="govuk-pagination__link-title">Next<span class="govuk-visually-hidden"> page</span></span>
                      <svg class="govuk-pagination__icon govuk-pagination__icon--next" xmlns="http://www.w3.org/2000/svg"
                           height="13" width="15" aria-hidden="true" focusable="false" viewBox="0 0 15 13">
                        <path d="m8.108-0.0088125-1.4136 1.414 4.2926 4.293h-12.986v2h12.896l-4.1855 3.9766 1.377 1.4492 6.7441-6.4062-6.7246-6.7266z"></path>
                      </svg>
                    </a>
                  </div>
                }
              </nav>
            }
        }
      </div>

    </div>
</div>

@section Scripts {
  <script asp-add-nonce type="module">
        import * as MOJFrontend from '/js/moj-frontend.min.js'
        MOJFrontend.initAll()
  </script>
  <script src="~/js/filter-toggle.js"></script>
}

<style asp-add-nonce>
    /* Mobile filter toggle button - hidden by default */
    .mobile-filter-toggle {
        display: none;
        width: 100%;
        margin-bottom: 20px;
    }

    /* Show toggle button only on mobile/tablet */
    @@media (max-width: 768px) {
        .mobile-filter-toggle {
            display: block;
        }

        /* Filter section transitions */
        .filter-section {
            overflow: hidden;
            transition: max-height 0.3s ease-in-out;
        }

        .filter-section.collapsed {
            max-height: 0;
            margin-bottom: 0;
        }
    }

    /* Ensure proper stacking on mobile */
    @@media (max-width: 768px) {
        .govuk-grid-column-one-third {
            width: 100%;
            margin-bottom: 30px;
        }

        .govuk-grid-column-two-thirds {
            width: 100%;
        }
    }

    @@media (max-width: 40.0625em) {
      .govuk-pagination__list .govuk-pagination__item {
        display: inline-block;
      }
    }
    
    #filterSection > div > div.govuk-summary-card__content > div > div > div > p
    {
      margin-top: 20px;
    }
    
    #filterSection div.govuk-summary-list__row:not(:first-child) div.govuk-form-group {
      margin-top: 20px;
    }
    
</style>